export const Movies=[
 {image: "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg",name: "Avengers", stars: 4,trailer:"https://www.youtube.com/watch?v=eOrNdBpGMv8",description:"There’s a hard truth out there known by even the most successful screenwriters – the ones with the Oscars and high-powered agents and six-figure deals. It’s a sneaky little notion that can seem upsetting and make the hard work you pour into your screenwriting feel futile."},

 {image: "https://pbs.twimg.com/media/D5JfxcgUUAEgu41.jpg",name: "After", stars:3,trailer:"https://www.youtube.com/watch?v=2SvwX3ux_-8c",description:"There’s a hard truth out there known by even the most successful screenwriters – the ones with the Oscars and high-powered agents and six-figure deals. It’s a sneaky little notion that can seem upsetting and make the hard work you pour into your screenwriting feel futile." },

 {image: "https://upload.wikimedia.org/wikipedia/en/1/19/Titanic_%28Official_Film_Poster%29.png",name: "Titanic", stars:5,trailer:"https://www.youtube.com/watch?v=kVrqfYjkTdQ",description:"There’s a hard truth out there known by even the most successful screenwriters – the ones with the Oscars and high-powered agents and six-figure deals. It’s a sneaky little notion that can seem upsetting and make the hard work you pour into your screenwriting feel futile." },

 {image: "https://upload.wikimedia.org/wikipedia/en/2/29/Movie_poster_for_%22Scary_Movie%22.jpg",name: "Scary movie", stars:2,trailer:"https://www.youtube.com/watch?v=HTLPULt0eJ4",description:"There’s a hard truth out there known by even the most successful screenwriters – the ones with the Oscars and high-powered agents and six-figure deals. It’s a sneaky little notion that can seem upsetting and make the hard work you pour into your screenwriting feel futile." },

 {image: "https://www.coastalbreezenews.com/wp-content/uploads/2020/04/21-bridges-139228.jpg",name: "21 bridges", stars:4,trailer:"https://www.youtube.com/watch?v=BVZDhunTrYA",description:"There’s a hard truth out there known by even the most successful screenwriters – the ones with the Oscars and high-powered agents and six-figure deals. It’s a sneaky little notion that can seem upsetting and make the hard work you pour into your screenwriting feel futile." }
]
